import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { supabase } from '../lib/supabaseClient';
import { Award, ShieldCheck, CreditCard, Plus, Calendar, Users, TrendingUp, DollarSign, ArrowLeft, Edit2, List, BarChart2, CheckCircle2, Clipboard, ShoppingBag } from 'lucide-react';
import './AgencyDashboardView.css';

const generateUUID = () => {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};

export default function AgencyDashboardView() {
  const { user } = useAuth();
  const navigate = useNavigate();

  // Core agency state
  const [agency, setAgency] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('trips');

  // Paywall / Stripe modal states
  const [showCheckoutModal, setShowCheckoutModal] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState(null);
  const [checkoutForm, setCheckoutForm] = useState({
    companyName: '',
    websiteUrl: '',
    logoUrl: '',
    cardNumber: '',
    expiry: '',
    cvv: ''
  });
  const [processingPayment, setProcessingPayment] = useState(false);

  // Trips & Itinerary editor states
  const [agencyTrips, setAgencyTrips] = useState([]);
  const [showCreateTripModal, setShowCreateTripModal] = useState(false);
  const [tripForm, setTripForm] = useState({ 
    name: '', 
    destination: '', 
    startDate: '', 
    endDate: '',
    isPublicPackage: false,
    packagePrice: '199',
    packageDescription: ''
  });
  const [creatingTrip, setCreatingTrip] = useState(false);

  // Itinerary items editing states
  const [selectedTripForItinerary, setSelectedTripForItinerary] = useState(null);
  const [itinerarySpots, setItinerarySpots] = useState([]);
  const [savingItinerary, setSavingItinerary] = useState(false);

  // Leads & Bookings state
  const [leads, setLeads] = useState([]);
  const [bookings, setBookings] = useState([]);

  // Fetch all agency data (profile, trips, leads, bookings)
  const fetchAgencyData = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    try {
      // 1. Fetch Agency Profile
      let agencyProfile = null;
      try {
        const { data, error } = await supabase
          .from('agency_profiles')
          .select('*')
          .eq('profile_id', user.id)
          .maybeSingle();
        
        if (!error && data) {
          agencyProfile = data;
        }
      } catch (err) {
        console.warn('DB error fetching agency, using localStorage fallback', err);
      }

      // Check LocalStorage fallback
      if (!agencyProfile) {
        const localAgency = localStorage.getItem(`spota_agency_${user.id}`);
        if (localAgency) {
          agencyProfile = JSON.parse(localAgency);
        }
      }

      setAgency(agencyProfile);

      if (agencyProfile) {
        // 2. Fetch trips generated by this agency
        let tripsList = [];
        try {
          const { data, error } = await supabase
            .from('trips')
            .select('*')
            .eq('agency_id', agencyProfile.id)
            .order('created_at', { ascending: false });
          
          if (!error && data) {
            tripsList = data;
          }
        } catch (err) {
          console.warn('DB error fetching agency trips, using localStorage fallback', err);
        }

        // Local storage fallback for agency trips
        const localTripsKey = `spota_agency_trips_${agencyProfile.id}`;
        const localTrips = localStorage.getItem(localTripsKey);
        if (tripsList.length === 0 && localTrips) {
          tripsList = JSON.parse(localTrips);
        }
        setAgencyTrips(tripsList);

        // 3. Fetch leads
        let leadsList = [];
        try {
          const { data, error } = await supabase
            .from('agency_leads')
            .select(`
              id,
              clicked_at,
              source_platform,
              spot_id,
              visitor_id,
              spots:spot_id ( title ),
              profiles:visitor_id ( username )
            `)
            .eq('agency_id', agencyProfile.id)
            .order('clicked_at', { ascending: false });

          if (!error && data) {
            leadsList = data.map(lead => ({
              id: lead.id,
              clicked_at: lead.clicked_at,
              source_platform: lead.source_platform,
              spot_name: lead.spots?.title || 'Unknown Spot',
              visitor_name: lead.profiles?.username || 'Guest Explorer',
              commission: 3.50
            }));
          }
        } catch (err) {
          console.warn('DB error fetching agency leads, generating simulated leads', err);
        }

        // Seed mock leads if none exist to make the dashboard look rich and active!
        if (leadsList.length === 0) {
          const mockLeads = [
            { id: '1', clicked_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(), source_platform: 'trip_board', spot_name: 'Alpine River Campsite', visitor_name: 'Sarah Jenkins', commission: 4.50 },
            { id: '2', clicked_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(), source_platform: 'spot_details', spot_name: 'Parvati Cafe & Bakery', visitor_name: 'Liam O\'Connor', commission: 1.50 },
            { id: '3', clicked_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), source_platform: 'trip_board', spot_name: 'Mountain Pass Viewpoint', visitor_name: 'Emma Watson', commission: 5.00 },
            { id: '4', clicked_at: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(), source_platform: 'instagram_recap', spot_name: 'Secret Waterfall Trail', visitor_name: 'Rahul Sharma', commission: 3.00 },
            { id: '5', clicked_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), source_platform: 'spot_details', spot_name: 'Boutique Forest Lodge', visitor_name: 'Jessica Taylor', commission: 8.50 }
          ];
          leadsList = mockLeads;
        }
        setLeads(leadsList);

        // 4. Fetch Direct Package Bookings
        let bookingsList = [];
        try {
          const { data, error } = await supabase
            .from('package_bookings')
            .select(`
              id,
              amount_paid,
              travelers_count,
              booking_date,
              status,
              user_id,
              profiles:user_id ( username ),
              trips:trip_id ( name )
            `)
            .order('booking_date', { ascending: false });

          if (!error && data) {
            bookingsList = data.map(b => ({
              id: b.id,
              amount_paid: parseFloat(b.amount_paid),
              travelers_count: b.travelers_count,
              booking_date: b.booking_date,
              status: b.status,
              buyer_name: b.profiles?.username || 'Client Explorer',
              package_name: b.trips?.name || 'Curated Tour'
            }));
          }
        } catch (err) {
          console.warn('DB error fetching bookings, using mock storage fallback', err);
        }

        // Local storage fallback check
        const localBookingsKey = `spota_agency_bookings_${agencyProfile.id}`;
        const localBookings = localStorage.getItem(localBookingsKey);
        if (bookingsList.length === 0 && localBookings) {
          bookingsList = JSON.parse(localBookings);
        }

        // Seed mock bookings if empty
        if (bookingsList.length === 0) {
          bookingsList = [
            { id: 'b1', booking_date: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), travelers_count: 2, amount_paid: 398.00, status: 'paid', buyer_name: 'David Miller', package_name: 'Kasol Wilderness Exploration' },
            { id: 'b2', booking_date: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(), travelers_count: 1, amount_paid: 199.00, status: 'paid', buyer_name: 'Marcus Sterling', package_name: 'Kasol Wilderness Exploration' }
          ];
          localStorage.setItem(localBookingsKey, JSON.stringify(bookingsList));
        }
        setBookings(bookingsList);
      }
    } catch (err) {
      console.error('Error fetching agency data:', err);
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    const timer = setTimeout(() => {
      fetchAgencyData();
    }, 0);
    return () => clearTimeout(timer);
  }, [fetchAgencyData]);

  // Handle Stripe Subscription simulation
  const handleOpenCheckout = (plan) => {
    setSelectedPlan(plan);
    setShowCheckoutModal(true);
  };

  const handleCheckoutSubmit = async (e) => {
    e.preventDefault();
    if (!checkoutForm.companyName.trim()) {
      alert('Company Name is required.');
      return;
    }
    setProcessingPayment(true);

    // Simulate payment loading
    setTimeout(async () => {
      try {
        const insertProfile = {
          profile_id: user.id,
          company_name: checkoutForm.companyName.trim(),
          website_url: checkoutForm.websiteUrl.trim() || null,
          logo_url: checkoutForm.logoUrl.trim() || null,
          subscription_tier: selectedPlan.tier,
          subscription_status: 'active',
          verified_at: new Date().toISOString(),
          created_at: new Date().toISOString()
        };

        let finalAgencyProfile = { ...insertProfile };

        // Attempt Supabase insert
        try {
          const { data, error } = await supabase
            .from('agency_profiles')
            .insert(insertProfile)
            .select()
            .single();
          
          if (error) throw error;
          if (data) {
            finalAgencyProfile = data;
          }
        } catch (dbErr) {
          console.warn('Direct database insert failed, caching agency details locally:', dbErr);
          // Fallback to client-generated UUID for offline LocalStorage simulation
          finalAgencyProfile.id = generateUUID();
        }

        // Store locally
        localStorage.setItem(`spota_agency_${user.id}`, JSON.stringify(finalAgencyProfile));
        setAgency(finalAgencyProfile);
        setShowCheckoutModal(false);
        setCheckoutForm({ companyName: '', websiteUrl: '', logoUrl: '', cardNumber: '', expiry: '', cvv: '' });
        
        // Dispatch event so profile updates badges
        window.dispatchEvent(new Event('spota_saves_updated'));
        alert(`Congratulations! "${finalAgencyProfile.company_name}" has been registered successfully. Plan: ${selectedPlan.name}`);
        
        fetchAgencyData();
      } catch (err) {
        console.error('Failed mock checkout onboarding:', err);
        alert('Payment processed, but profile sync failed: ' + err.message);
      } finally {
        setProcessingPayment(false);
      }
    }, 1500);
  };

  // Create co-branded client trip
  const handleCreateClientTrip = async (e) => {
    e.preventDefault();
    if (!agency) return;
    if (!tripForm.name.trim()) {
      alert('Trip name is required.');
      return;
    }
    setCreatingTrip(true);

    try {
      const inviteCode = Math.random().toString(36).substring(2, 10).toUpperCase();
      const insertTrip = {
        name: tripForm.name.trim(),
        destination: tripForm.destination.trim() || null,
        start_date: tripForm.startDate || null,
        end_date: tripForm.endDate || null,
        invite_code: inviteCode,
        creator_id: user.id,
        agency_id: agency.id,
        is_cobranded: true,
        is_public_package: tripForm.isPublicPackage,
        package_price: tripForm.isPublicPackage ? (parseFloat(tripForm.packagePrice) || 0) : 0,
        package_description: tripForm.isPublicPackage ? tripForm.packageDescription : null,
        slots_total: 20,
        slots_booked: 0,
        created_at: new Date().toISOString()
      };

      let finalTrip = { ...insertTrip };

      // 1. Write to Supabase trips
      try {
        const { data: dbTrip, error: tripError } = await supabase
          .from('trips')
          .insert(insertTrip)
          .select()
          .single();

        if (tripError) throw tripError;
        if (dbTrip) {
          finalTrip = dbTrip;
        }

        // Add creator as member
        await supabase
          .from('trip_members')
          .insert({
            trip_id: finalTrip.id,
            user_id: user.id,
            role: 'creator'
          });
      } catch (dbErr) {
        console.warn('DB trip creation failed, executing local simulation fallback:', dbErr);
        // Fallback to client-generated UUID for offline simulation
        finalTrip.id = generateUUID();
      }

      // Local storage list save
      const localTripsKey = `spota_agency_trips_${agency.id}`;
      const existingLocalTrips = JSON.parse(localStorage.getItem(localTripsKey) || '[]');
      const updatedLocalTrips = [finalTrip, ...existingLocalTrips];
      localStorage.setItem(localTripsKey, JSON.stringify(updatedLocalTrips));

      // Mock memberships if offline/mock
      const localTripMembersKey = `spota_trip_members_${finalTrip.id}`;
      localStorage.setItem(localTripMembersKey, JSON.stringify([
        { user_id: user.id, role: 'creator', profiles: { username: agency.company_name } }
      ]));

      alert(tripForm.isPublicPackage 
        ? `Trip Package "${finalTrip.name}" is now live in the Marketplace catalog!`
        : `Client Trip Board created! Give invite code to clients: ${inviteCode}`
      );
      setTripForm({ name: '', destination: '', startDate: '', endDate: '', isPublicPackage: false, packagePrice: '199', packageDescription: '' });
      setShowCreateTripModal(false);
      fetchAgencyData();
    } catch (err) {
      console.error('Failed creating client trip:', err);
      alert('Failed creating trip: ' + err.message);
    } finally {
      setCreatingTrip(false);
    }
  };

  // Load spots for itinerary configuration
  const handleOpenItineraryEditor = async (tripItem) => {
    setSelectedTripForItinerary(tripItem);
    setActiveTab('itinerary');
    setSavingItinerary(false);

    try {
      // Fetch trip spots
      let spotsList = [];
      try {
        const { data, error } = await supabase
          .from('trip_spots')
          .select(`
            trip_id,
            spot_id,
            visited,
            itinerary_day,
            schedule_time,
            booking_cta_label,
            booking_cta_url,
            spots:spot_id (
              id,
              title,
              category
            )
          `)
          .eq('trip_id', tripItem.id);
        
        if (!error && data) {
          spotsList = data;
        }
      } catch (dbErr) {
        console.warn('DB fetch trip spots failed, checking local mocks', dbErr);
      }

      // Check LocalStorage fallback
      const localSpotsKey = `spota_trip_spots_${tripItem.id}`;
      const localSpots = localStorage.getItem(localSpotsKey);
      if (spotsList.length === 0 && localSpots) {
        const parsedLocalSpots = JSON.parse(localSpots);
        // Map structure to simulate DB query
        spotsList = parsedLocalSpots.map(s => ({
          trip_id: tripItem.id,
          spot_id: s.id || s.spot_id,
          visited: s.visited || false,
          itinerary_day: s.itinerary_day || 1,
          schedule_time: s.schedule_time || '',
          booking_cta_label: s.booking_cta_label || 'Book Spot',
          booking_cta_url: s.booking_cta_url || '',
          spots: {
            id: s.id || s.spot_id,
            title: s.title || s.spots?.title || 'Adventure Spot',
            category: s.category || s.spots?.category || 'trail'
          }
        }));
      }

      setItinerarySpots(spotsList);
    } catch (err) {
      console.error('Failed loading itinerary spots:', err);
      alert('Failed to load itinerary spots.');
    }
  };

  const handleItineraryFieldChange = (spotId, field, value) => {
    setItinerarySpots(prev => 
      prev.map(item => item.spot_id === spotId ? { ...item, [field]: value } : item)
    );
  };

  const handleSaveItinerary = async () => {
    if (!selectedTripForItinerary) return;
    setSavingItinerary(true);

    try {
      // 1. Try DB writes
      let dbFailed = false;
      for (const item of itinerarySpots) {
        try {
          const { error } = await supabase
            .from('trip_spots')
            .update({
              itinerary_day: parseInt(item.itinerary_day) || 1,
              schedule_time: item.schedule_time || null,
              booking_cta_label: item.booking_cta_label || null,
              booking_cta_url: item.booking_cta_url || null
            })
            .eq('trip_id', selectedTripForItinerary.id)
            .eq('spot_id', item.spot_id);
          
          if (error) dbFailed = true;
        } catch (err) {
          console.warn('Trip spot update error', err);
          dbFailed = true;
        }
      }

      // 2. Local Storage sync backup
      const localSpotsKey = `spota_trip_spots_${selectedTripForItinerary.id}`;
      const localSpots = JSON.parse(localStorage.getItem(localSpotsKey) || '[]');
      
      const updatedLocalSpots = localSpots.map(ls => {
        const editorItem = itinerarySpots.find(item => item.spot_id === ls.id || item.spot_id === ls.spot_id);
        if (editorItem) {
          return {
            ...ls,
            itinerary_day: parseInt(editorItem.itinerary_day) || 1,
            schedule_time: editorItem.schedule_time || '',
            booking_cta_label: editorItem.booking_cta_label || 'Book Spot',
            booking_cta_url: editorItem.booking_cta_url || ''
          };
        }
        return ls;
      });

      localStorage.setItem(localSpotsKey, JSON.stringify(updatedLocalSpots));
      
      alert(dbFailed 
        ? 'Itinerary updated locally (Supabase remote DB tables pending).'
        : 'Itinerary details saved successfully!'
      );
    } catch (err) {
      console.error('Failed saving itinerary details:', err);
      alert('Failed to save itinerary details.');
    } finally {
      setSavingItinerary(false);
    }
  };

  // Copy code helper
  const handleCopyCode = (code) => {
    navigator.clipboard.writeText(code);
    alert(`Invite code "${code}" copied to clipboard! Share it with your clients.`);
  };

  if (loading) {
    return (
      <div className="agency-dashboard-loading">
        <div className="pulse-loader"></div>
        <p>Loading Agency Hub...</p>
      </div>
    );
  }

  // --- RENDERING UNSUBSCRIBED STATE ---
  if (!agency) {
    const plans = [
      {
        tier: 'boutique',
        name: 'Boutique Plan',
        price: '$49',
        color: '#6C8C74',
        desc: 'Best for local guides and weekend group coordinators.',
        features: [
          'Up to 5 active client groups',
          'Verified B2B profile page',
          'Basic itinerary day sorting',
          'Standard map pin integration'
        ]
      },
      {
        tier: 'professional',
        name: 'Professional Plan',
        price: '$149',
        color: '#8e44ad',
        popular: true,
        desc: 'Ideal for growing travel agencies and trek coordinators.',
        features: [
          'Unlimited active client groups',
          'Direct affiliate & booking CTAs',
          'Co-branded Wrapped Recaps',
          'Full-screen Vibes Feed promo',
          'Dedicated support manager'
        ]
      },
      {
        tier: 'enterprise',
        name: 'Enterprise Scale',
        price: '$399',
        color: '#d35400',
        desc: 'For high-volume operators requiring automated scheduling.',
        features: [
          'Everything in Professional Plan',
          'API access for automated code gen',
          'Custom domain integration',
          'Interactive analytics exports',
          'White-labeled recaps (No Spota logo)'
        ]
      }
    ];

    return (
      <div className="agency-paywall-container animate-fade-in">
        <div className="paywall-header glass-panel">
          <button className="paywall-back" onClick={() => navigate('/profile')}>
            <ArrowLeft size={18} /> Back to Profile
          </button>
          <div className="brand-badge"><Award size={20} /> SPOTA PARTNER HUB</div>
          <h1>Scale Your Travel Agency & Monetize Group Trips</h1>
          <p>Deliver interactive live itineraries, coordinate check-ins, and earn commissions on bookings.</p>
        </div>

        <div className="plans-grid">
          {plans.map((plan) => (
            <div key={plan.tier} className={`plan-card glass-panel ${plan.popular ? 'popular' : ''}`}>
              {plan.popular && <span className="popular-badge">RECOMMENDED</span>}
              <h3 style={{ color: plan.color }}>{plan.name}</h3>
              <div className="plan-price">
                <span className="price-num">{plan.price}</span>
                <span className="price-period">/ month</span>
              </div>
              <p className="plan-desc">{plan.desc}</p>
              
              <ul className="plan-features">
                {plan.features.map((f, i) => (
                  <li key={i}><CheckCircle2 size={16} color="var(--color-accent)" /> {f}</li>
                ))}
              </ul>

              <button 
                className="plan-cta-btn" 
                style={{ backgroundColor: plan.color }}
                onClick={() => handleOpenCheckout(plan)}
              >
                Get Started
              </button>
            </div>
          ))}
        </div>

        {/* CHECKOUT MODAL (STRIPE SIMULATOR) */}
        {showCheckoutModal && selectedPlan && (
          <div className="checkout-modal-backdrop">
            <div className="checkout-modal glass-panel animate-fade-in">
              <div className="checkout-header">
                <h3>Subscribe to {selectedPlan.name}</h3>
                <button className="close-checkout" onClick={() => setShowCheckoutModal(false)}>×</button>
              </div>

              <form onSubmit={handleCheckoutSubmit}>
                <div className="checkout-section-title">Company Profile</div>
                <div className="form-group">
                  <label>Company Name *</label>
                  <input 
                    type="text" 
                    placeholder="e.g. Wanderlust Horizons Co." 
                    value={checkoutForm.companyName}
                    onChange={(e) => setCheckoutForm({ ...checkoutForm, companyName: e.target.value })}
                    required 
                    className="zen-input"
                  />
                </div>
                <div className="form-group-row">
                  <div className="form-group">
                    <label>Website URL</label>
                    <input 
                      type="url" 
                      placeholder="e.g. https://myagency.com" 
                      value={checkoutForm.websiteUrl}
                      onChange={(e) => setCheckoutForm({ ...checkoutForm, websiteUrl: e.target.value })}
                      className="zen-input"
                    />
                  </div>
                  <div className="form-group">
                    <label>Logo URL (PNG)</label>
                    <input 
                      type="url" 
                      placeholder="e.g. https://mylogo.png" 
                      value={checkoutForm.logoUrl}
                      onChange={(e) => setCheckoutForm({ ...checkoutForm, logoUrl: e.target.value })}
                      className="zen-input"
                    />
                  </div>
                </div>

                <div className="checkout-section-title" style={{ marginTop: '16px' }}><CreditCard size={16} /> Stripe Card Details</div>
                <div className="form-group">
                  <label>Card Number</label>
                  <input 
                    type="text" 
                    placeholder="4242 •••• •••• 4242" 
                    maxLength={16}
                    value={checkoutForm.cardNumber}
                    onChange={(e) => setCheckoutForm({ ...checkoutForm, cardNumber: e.target.value })}
                    className="zen-input"
                  />
                </div>
                <div className="form-group-row">
                  <div className="form-group">
                    <label>Expiration Date</label>
                    <input 
                      type="text" 
                      placeholder="MM/YY" 
                      maxLength={5}
                      value={checkoutForm.expiry}
                      onChange={(e) => setCheckoutForm({ ...checkoutForm, expiry: e.target.value })}
                      className="zen-input"
                    />
                  </div>
                  <div className="form-group">
                    <label>CVC / CVV</label>
                    <input 
                      type="password" 
                      placeholder="•••" 
                      maxLength={3}
                      value={checkoutForm.cvv}
                      onChange={(e) => setCheckoutForm({ ...checkoutForm, cvv: e.target.value })}
                      className="zen-input"
                    />
                  </div>
                </div>

                <button type="submit" className="checkout-pay-btn" disabled={processingPayment}>
                  {processingPayment ? 'Processing Secure Stripe payment...' : `Authorize Payment of ${selectedPlan.price}`}
                </button>
                <span className="stripe-secure-msg">🔒 Secured by Stripe. Simulated sandbox transaction.</span>
              </form>
            </div>
          </div>
        )}
      </div>
    );
  }

  // --- RENDERING SUBSCRIBED DASHBOARD STATE ---
  const leadEarnings = leads.reduce((sum, lead) => sum + (lead.commission || 3.0), 0);
  const packageEarnings = bookings.reduce((sum, booking) => sum + (booking.amount_paid || 0), 0);
  const totalCommissions = leadEarnings + (packageEarnings * 0.95); // 95% split payout for agency

  return (
    <div className="agency-dashboard-container animate-fade-in">
      {/* Top Banner Toolbar */}
      <div className="agency-header glass-panel">
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button className="agency-back-btn" onClick={() => navigate('/profile')}>
            <ArrowLeft size={18} />
          </button>
          <div>
            <h2>{agency.company_name}</h2>
            <span className="agency-badge-label">
              <ShieldCheck size={14} /> Verified Partner · {agency.subscription_tier.toUpperCase()} TIER
            </span>
          </div>
        </div>
        <button className="agency-add-btn" onClick={() => setShowCreateTripModal(true)}>
          <Plus size={16} /> Create Client Trip
        </button>
      </div>

      {/* Analytics Dashboard Grid */}
      <div className="analytics-dashboard-grid">
        <div className="metric-card glass-panel">
          <div className="metric-icon" style={{ backgroundColor: 'rgba(108, 140, 116, 0.15)', color: 'var(--color-accent)' }}>
            <Users size={20} />
          </div>
          <div className="metric-info">
            <span className="metric-title">Active Groups</span>
            <span className="metric-val">{agencyTrips.length}</span>
          </div>
        </div>

        <div className="metric-card glass-panel">
          <div className="metric-icon" style={{ backgroundColor: 'rgba(142, 68, 173, 0.15)', color: '#8e44ad' }}>
            <ShoppingBag size={20} />
          </div>
          <div className="metric-info">
            <span className="metric-title">Direct Bookings</span>
            <span className="metric-val">{bookings.length}</span>
          </div>
        </div>

        <div className="metric-card glass-panel">
          <div className="metric-icon" style={{ backgroundColor: 'rgba(211, 84, 0, 0.15)', color: '#d35400' }}>
            <TrendingUp size={20} />
          </div>
          <div className="metric-info">
            <span className="metric-title">Marketplace Clicks</span>
            <span className="metric-val">{leads.length}</span>
          </div>
        </div>

        <div className="metric-card glass-panel">
          <div className="metric-icon" style={{ backgroundColor: 'rgba(39, 174, 96, 0.15)', color: '#27ae60' }}>
            <DollarSign size={20} />
          </div>
          <div className="metric-info">
            <span className="metric-title">Agency Revenue</span>
            <span className="metric-val">${totalCommissions.toFixed(2)}</span>
          </div>
        </div>
      </div>

      {/* Main Tabs Navigation */}
      <div className="agency-tabs">
        <button 
          className={`tab-btn ${activeTab === 'trips' ? 'active' : ''}`}
          onClick={() => setActiveTab('trips')}
        >
          <List size={16} /> Active Trips ({agencyTrips.length})
        </button>
        <button 
          className={`tab-btn ${activeTab === 'itinerary' ? 'active' : ''}`}
          onClick={() => {
            if (!selectedTripForItinerary && agencyTrips.length > 0) {
              handleOpenItineraryEditor(agencyTrips[0]);
            } else {
              setActiveTab('itinerary');
            }
          }}
          disabled={agencyTrips.length === 0}
        >
          <Edit2 size={16} /> Itinerary & CTA Planner
        </button>
        <button 
          className={`tab-btn ${activeTab === 'leads' ? 'active' : ''}`}
          onClick={() => setActiveTab('leads')}
        >
          <BarChart2 size={16} /> Bookings & Payouts Ledger
        </button>
      </div>

      {/* Tab Contents */}
      <div className="dashboard-content">
        {/* TRIPS TAB */}
        {activeTab === 'trips' && (
          <div className="trips-tab-content">
            {agencyTrips.length === 0 ? (
              <div className="empty-dashboard-state glass-panel">
                <Calendar size={40} />
                <h4>No Client Trips Built Yet</h4>
                <p>Create a customized client trip, assign it an invite code, and link it with co-branding parameters.</p>
                <button className="agency-add-btn" onClick={() => setShowCreateTripModal(true)}>
                  Create Client Trip
                </button>
              </div>
            ) : (
              <div className="dashboard-trips-table glass-panel">
                <table className="agency-table">
                  <thead>
                    <tr>
                      <th>Trip Board Name</th>
                      <th>Destination</th>
                      <th>Dates</th>
                      <th>Invite Code / Type</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {agencyTrips.map((trip) => (
                      <tr key={trip.id}>
                        <td className="trip-cell-title">{trip.name}</td>
                        <td>{trip.destination || 'Flexible Route'}</td>
                        <td>
                          {trip.start_date 
                            ? `${new Date(trip.start_date).toLocaleDateString([], {month: 'short', day: 'numeric'})} - ${new Date(trip.end_date).toLocaleDateString([], {month: 'short', day: 'numeric', year: 'numeric'})}`
                            : 'Flexible Dates'
                          }
                        </td>
                        <td>
                          {trip.is_public_package ? (
                            <span className="source-tag spot_details" style={{ fontSize: '10px' }}>
                              🏷️ marketplace (${trip.package_price})
                            </span>
                          ) : (
                            <div className="code-copy-cell">
                              <span className="code-pill">{trip.invite_code}</span>
                              <button className="copy-code-btn" onClick={() => handleCopyCode(trip.invite_code)} title="Copy Code">
                                <Clipboard size={14} />
                              </button>
                            </div>
                          )}
                        </td>
                        <td>
                          <div style={{ display: 'flex', gap: '8px' }}>
                            <button className="row-action-btn primary" onClick={() => handleOpenItineraryEditor(trip)}>
                              Plan Itinerary
                            </button>
                            <button className="row-action-btn secondary" onClick={() => navigate(`/trips/${trip.id}`)}>
                              View Board
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* ITINERARY TAB */}
        {activeTab === 'itinerary' && selectedTripForItinerary && (
          <div className="itinerary-tab-content animate-fade-in">
            <div className="itinerary-config-header glass-panel">
              <div>
                <span className="config-label">Configuring Itinerary for:</span>
                <h3>{selectedTripForItinerary.name}</h3>
              </div>
              <div className="config-selector">
                <label>Change Trip: </label>
                <select 
                  value={selectedTripForItinerary.id} 
                  onChange={(e) => {
                    const found = agencyTrips.find(t => t.id === e.target.value);
                    if (found) handleOpenItineraryEditor(found);
                  }}
                  className="zen-select"
                >
                  {agencyTrips.map(t => (
                    <option key={t.id} value={t.id}>{t.name}</option>
                  ))}
                </select>
              </div>
            </div>

            <div className="itinerary-spots-editor glass-panel">
              {itinerarySpots.length === 0 ? (
                <div className="empty-itinerary-state">
                  <Clipboard size={32} />
                  <p>No spots have been pinned to this trip yet.</p>
                  <span>First, enter the trip board as creator, add locations from the Spota map database, and then reload this dashboard page to customize day tracks and booking CTAs!</span>
                  <button className="agency-add-btn" style={{ marginTop: '16px' }} onClick={() => navigate(`/trips/${selectedTripForItinerary.id}`)}>
                    Go to Trip Board
                  </button>
                </div>
              ) : (
                <>
                  <div className="spots-editor-grid">
                    {itinerarySpots.map((item) => (
                      <div key={item.spot_id} className="spot-editor-card glass-panel">
                        <div className="spot-card-title">
                          <h4>{item.spots?.title}</h4>
                          <span className="spot-card-cat">{item.spots?.category}</span>
                        </div>

                        <div className="editor-row">
                          <div className="form-group flex-1">
                            <label>Itinerary Day</label>
                            <input 
                              type="number" 
                              min="1" 
                              value={item.itinerary_day || ''}
                              onChange={(e) => handleItineraryFieldChange(item.spot_id, 'itinerary_day', e.target.value)}
                              className="zen-input"
                              placeholder="e.g. 1"
                            />
                          </div>
                          <div className="form-group flex-2">
                            <label>Arrival Schedule Time</label>
                            <input 
                              type="text" 
                              value={item.schedule_time || ''}
                              onChange={(e) => handleItineraryFieldChange(item.spot_id, 'schedule_time', e.target.value)}
                              className="zen-input"
                              placeholder="e.g. 10:30 AM"
                            />
                          </div>
                        </div>

                        <div className="editor-row">
                          <div className="form-group flex-1">
                            <label>Booking CTA Button Text</label>
                            <input 
                              type="text" 
                              value={item.booking_cta_label || ''}
                              onChange={(e) => handleItineraryFieldChange(item.spot_id, 'booking_cta_label', e.target.value)}
                              className="zen-input"
                              placeholder="e.g. Book Rafting"
                            />
                          </div>
                        </div>

                        <div className="editor-row">
                          <div className="form-group flex-1">
                            <label>Affiliate / Booking Link URL</label>
                            <input 
                              type="url" 
                              value={item.booking_cta_url || ''}
                              onChange={(e) => handleItineraryFieldChange(item.spot_id, 'booking_cta_url', e.target.value)}
                              className="zen-input"
                              placeholder="e.g. https://booking.com/tours/123"
                            />
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="itinerary-actions-footer">
                    <button 
                      className="save-itinerary-btn" 
                      onClick={handleSaveItinerary}
                      disabled={savingItinerary}
                    >
                      {savingItinerary ? 'Saving Details...' : 'Save Itinerary & CTA Setup'}
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        )}

        {/* LEADS & BOOKINGS TAB */}
        {activeTab === 'leads' && (
          <div className="leads-tab-content animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
            {/* Direct Bookings section */}
            <div className="dashboard-trips-table glass-panel">
              <div className="table-caption-bar">
                <h3>Direct Marketplace Package Sales</h3>
                <span className="com-banner">Marketplace Payout Split: <strong>95% Agency / 5% Spota fee</strong></span>
              </div>
              {bookings.length === 0 ? (
                <p style={{ textAlign: 'center', color: 'var(--color-text-secondary)', padding: '20px 0' }}>No direct package bookings logged yet.</p>
              ) : (
                <table className="agency-table">
                  <thead>
                    <tr>
                      <th>Buyer Client</th>
                      <th>Booked Itinerary Package</th>
                      <th>Travelers Count</th>
                      <th>Transaction Date</th>
                      <th>Gross Price</th>
                      <th>Your Payout (95%)</th>
                    </tr>
                  </thead>
                  <tbody>
                    {bookings.map((booking) => (
                      <tr key={booking.id}>
                        <td style={{ fontWeight: 600 }}>{booking.buyer_name}</td>
                        <td style={{ color: '#8e44ad', fontWeight: 600 }}>{booking.package_name}</td>
                        <td style={{ textAlign: 'center' }}>{booking.travelers_count} traveler(s)</td>
                        <td>{new Date(booking.booking_date).toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' })}</td>
                        <td style={{ fontWeight: 600 }}>${booking.amount_paid.toFixed(2)}</td>
                        <td style={{ color: '#27ae60', fontWeight: 700 }}>+${(booking.amount_paid * 0.95).toFixed(2)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>

            {/* Click Leads section */}
            <div className="dashboard-trips-table glass-panel">
              <div className="table-caption-bar">
                <h3>Affiliate & Ad Lead clicks</h3>
                <span className="com-banner">Estimated click payout rate: <strong>$3.00 - $8.50 per click</strong></span>
              </div>
              <table className="agency-table">
                <thead>
                  <tr>
                    <th>Explorer Client</th>
                    <th>Destination Spot</th>
                    <th>Referral Source</th>
                    <th>Click Timestamp</th>
                    <th>Payout Commission</th>
                  </tr>
                </thead>
                <tbody>
                  {leads.map((lead) => (
                    <tr key={lead.id}>
                      <td style={{ fontWeight: 600 }}>{lead.visitor_name}</td>
                      <td style={{ color: 'var(--color-accent)', fontWeight: 600 }}>{lead.spot_name}</td>
                      <td>
                        <span className={`source-tag ${lead.source_platform}`}>
                          {lead.source_platform.replace('_', ' ')}
                        </span>
                      </td>
                      <td>{new Date(lead.clicked_at).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</td>
                      <td style={{ color: '#27ae60', fontWeight: 700 }}>+${lead.commission.toFixed(2)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>

      {/* CREATE CLIENT TRIP MODAL */}
      {showCreateTripModal && (
        <div className="trips-modal-backdrop">
          <div className="trips-modal glass-panel animate-fade-in" style={{ maxWidth: '560px' }}>
            <div className="trips-modal-header">
              <h3>Create Client Board or Marketplace Package</h3>
              <button className="modal-close" onClick={() => setShowCreateTripModal(false)}>×</button>
            </div>
            <form onSubmit={handleCreateClientTrip}>
              <div className="form-group">
                <label>Trip Name</label>
                <input 
                  type="text" 
                  placeholder="e.g. Kasol Wilderness Exploration" 
                  value={tripForm.name}
                  onChange={(e) => setTripForm({ ...tripForm, name: e.target.value })}
                  className="zen-input"
                  required
                />
              </div>
              <div className="form-group">
                <label>Destination</label>
                <input 
                  type="text" 
                  placeholder="e.g. Kasol, Himachal Pradesh" 
                  value={tripForm.destination}
                  onChange={(e) => setTripForm({ ...tripForm, destination: e.target.value })}
                  className="zen-input"
                />
              </div>
              <div className="dates-row">
                <div className="form-group">
                  <label>Start Date</label>
                  <input 
                    type="date" 
                    value={tripForm.startDate}
                    onChange={(e) => setTripForm({ ...tripForm, startDate: e.target.value })}
                    className="zen-input"
                  />
                </div>
                <div className="form-group">
                  <label>End Date</label>
                  <input 
                    type="date" 
                    value={tripForm.endDate}
                    onChange={(e) => setTripForm({ ...tripForm, endDate: e.target.value })}
                    className="zen-input"
                  />
                </div>
              </div>

              {/* Marketplace Listing parameters */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', margin: '16px 0 12px 0' }}>
                <input 
                  type="checkbox" 
                  id="isPublicPackage"
                  checked={tripForm.isPublicPackage}
                  onChange={(e) => setTripForm({ ...tripForm, isPublicPackage: e.target.checked })}
                  style={{ width: '18px', height: '18px', accentColor: '#8e44ad', cursor: 'pointer' }}
                />
                <label htmlFor="isPublicPackage" style={{ fontWeight: 700, fontSize: '13px', cursor: 'pointer', color: 'var(--color-text-primary)' }}>
                  🏷️ Publish as Marketplace Trip Package
                </label>
              </div>

              {tripForm.isPublicPackage && (
                <div className="animate-fade-in" style={{ 
                  backgroundColor: 'rgba(142, 68, 173, 0.04)', 
                  padding: '16px', 
                  borderRadius: '12px', 
                  border: '1px solid rgba(142, 68, 173, 0.15)', 
                  marginBottom: '16px',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '12px'
                }}>
                  <div className="form-group">
                    <label>Package Price per Traveler (USD)</label>
                    <input 
                      type="number" 
                      placeholder="e.g. 199" 
                      min="1"
                      value={tripForm.packagePrice}
                      onChange={(e) => setTripForm({ ...tripForm, packagePrice: e.target.value })}
                      className="zen-input"
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Package Description & Highlights</label>
                    <textarea 
                      placeholder="e.g. Discover hidden hot springs, hike to mountain viewpoints, and enjoy cozy stays at verified camp resorts..." 
                      value={tripForm.packageDescription}
                      onChange={(e) => setTripForm({ ...tripForm, packageDescription: e.target.value })}
                      className="zen-input"
                      rows={3}
                      style={{ fontFamily: 'inherit', resize: 'vertical' }}
                    />
                  </div>
                </div>
              )}

              <button type="submit" className="submit-trip-btn" disabled={creatingTrip}>
                {creatingTrip ? 'Building Board...' : 'Create Board / Package'}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
